#  Loki's configuration file

auth_enabled: false #This means Loki is open to accept logs from any client without authentication.

server:
  http_listen_port: 3100 # Loki listens for HTTP requests (used by Grafana and Promtail)
  grpc_listen_port: 9095

ingester: #this section Controls how Loki stores incoming logs
  lifecycler:
    ring:
      kvstore:
        store: inmemory #storage is used, logs won’t persist after container restarts. if you want use "filesystem"
      replication_factor: 1
  #how long Loki holds logs before writing them to storage.
  #If this is set too high, recent logs may take longer to appear.
  chunk_idle_period: 5m 
  chunk_retain_period: 30s

#Defines how Loki stores and queries data:
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

#Defines how Loki handles storage:
storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/boltdb-shipper-active
    cache_location: /var/loki/boltdb-shipper-cache

#Defines limits for incoming logs
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false  # ✅ Disable structured metadata Fixes metadata schema issue
  retention_period: 24h #This is correct and should keep logs for 24 hours

#Defines how Loki compacts log chunks
compactor:
  retention_enabled: true  # Add this to activate log deletion
  working_directory: /var/loki/boltdb-shipper-compactor
  retention_delete_delay: 1h   # Delay before logs are deleted after retention expires
  delete_request_store: filesystem #boltdb-shipper  # ✅ Define delete request store

#Defines how Loki handles alerts (optional)
ruler:
  storage:
    type: local
    local:
      directory: /var/loki/rules